### ISSUE TITLE
Rust Code Compilation & Testing

### ISSUE THREAD

**Issue by saiSunkari19** [AutonomyNetwork/autonomy-chain#35]
To integrate Wasm into Autonomy Chain, @Sandeep is testing the current rust smart contract

**Comment by Sandeep-Narahari** [comment]
Completed here is the docs for cosmjs [      https://docs.google.com/document/d/1BG6OP3STpHHjhoKDBVuGNijA1nTDJgEO9fA_cRUIZeE/edit?usp=sharing](url)
